# This is a basic workflow to help you get started with Actions

name: Deploy Workflow

# Controls when the workflow will run
on:
 workflow_dispatch:
 push:
  branches: [main]
jobs:
 job_one:
  name: Deploy
  runs-on: Ubuntu-latest
  steps:
   - name: testing
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.HOST}}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      port: ${{ secrets.PORT }}
      script: |
       cd natiwb.github.io
       git pull
